### PR TITLE
Cross compile to Mac arm64

### LINKED ISSUE #73: Failure on MacBook M1
Hi,

I tried to build our software using the H3 library on a new MacBook M1. Unfortunately I do get the following error:

`java.lang.UnsatisfiedLinkError: No native resource found at /darwin-arm64/libh3-java.dylib
	at com.uber.h3core.H3CoreLoader.copyResource(H3CoreLoader.java:68)
	at com.uber.h3core.H3CoreLoader.loadNatives(H3CoreLoader.java:120)
	at com.uber.h3core.H3CoreLoader.loadNatives(H3CoreLoader.java:89)
	at com.uber.h3core.H3Core.newInstance(H3Core.java:79)`

I already found out that this is because there simply is no native library for the combination of operating system (darwin) and architecture (arm64). So my questions are: Is a fix already planned? Is there a workaround?

### PR DESCRIPTION
**Pull request by isaacbrodsky**
Fixes #73

Needs verification that the produced binary works as expected.

### CODE REVIEW

**Comment by isaacbrodsky** [comment]
Here's the snapshot JAR I generated (should have only Mac x64 and Mac arm64 binaries in it), uploaded as zip (just rename to jar). Could someone with physical M1 hardware test and confirm it works?
[h3-3.7.2-SNAPSHOT.zip](https://github.com/uber/h3-java/files/7644118/h3-3.7.2-SNAPSHOT.zip)

**Comment by g-derzhavets** [comment]
Hey @isaacbrodsky, I've tested your jar and it worked (no error about no native library). So I guess you can merged and release the new version? Btw, when do you think the next release will be?

**Comment by isaacbrodsky** [comment]
cc @nrabinowitz @ajfriend @dfellis

File: src/main/c/h3-java/build-h3.sh [hunk 1]
```diff
@@ -107,6 +107,42 @@ esac
 mkdir -p src/main/resources/$LIBRARY_DIR
 cp target/h3-java-build/lib/libh3-java* src/main/resources/$LIBRARY_DIR
 
+# Cross compile from Mac x64 to Mac arm64
+if [ "$(uname -sm)" == "Darwin x86_64" ]; then
```
Comment (dfellis) [inline src/main/c/h3-java/build-h3.sh:111]: Since I don't see any other conditionals, does this mean that anyone building on OS X also automatically builds the ARM variant? Do we need to do anything special with the publishing of this library to handle this?

Comment (isaacbrodsky) [reply src/main/c/h3-java/build-h3.sh:111]: Yes, right now the ARM (M1) binary is automatically built. As it is, releasing must be done from Mac OS since we do not have a cross compilation option for Mac OS x64 - https://github.com/uber/h3-java/blob/master/docs/releasing.md

Comment (dfellis) [reply src/main/c/h3-java/build-h3.sh:111]: Well, I don't know how much the Java community does this, but if someone wants to build the library locally and then use that, they'd do extra work for no apparent reason on there end.

Would it make sense to create a `RELEASE=true` environment variable that is set in the Github Actions build script and checked for here to add this extra behavior so anyone building locally builds just for their own platform by default?

Comment (g-derzhavets) [reply src/main/c/h3-java/build-h3.sh:111]: any news? :)

**Review by dfellis — APPROVED** [review]
